### ISSUE TITLE
Graphicscache not updated when input files are edited

### ISSUE THREAD

**Issue by MatthiasNieuwenhuisen** [xqms/graphicscache#3] opened 2018-10-04 15:35 UTC
If an already cached image file is edited, the cache is not updated when recompiling the LaTeX document.

**Comment by xqms** [comment] 2018-10-04 18:11
Hmm, I can't reproduce that here. The update check is based on the file modification time. Does your filename contain strange characters?

**Comment by MatthiasNieuwenhuisen** [comment] 2018-10-04 20:17
It seems that this happens if the file extension is not speficied.

In this example the first figure is updated as expected, while the second figure is not.

```latex
\documentclass{article}
\usepackage{graphicx}
\usepackage{graphicscache}
\begin{document}
\includegraphics[width=\linewidth]{left-fig.jpg}
\includegraphics[width=\linewidth]{left-fig}
\end{document}
```

**Comment by MatthiasNieuwenhuisen** [comment] 2018-10-05 09:13
Related:
[Graphics file extensions and their order of inclusion when not specified](https://tex.stackexchange.com/questions/72930/graphics-file-extensions-and-their-order-of-inclusion-when-not-specified)

**Comment by xqms** [comment] 2018-10-05 12:14
Here is code for finding the filename in the same manner as \includegraphics:

https://tex.stackexchange.com/questions/99070/check-for-a-valid-file-before-using-includegraphics/99099#99099

**Comment by xqms** [comment] 2018-10-05 18:47
Should be fixed in c4fa1b9.

**Closed** 2018-10-05 22:36 UTC
